name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      # Lint
      - run: |
          npm ci --ignore-scripts --audit=false
          npm run lint --if-present
