name: Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Setup
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      # Test
      - run: |
          npm ci --ignore-scripts --audit=false
          npm run test --if-present
